context:
  version: "0.0.8"

package:
  name: khiops-driver-azure
  version: ${{ version }}

source:
  - url: https://github.com/KhiopsML/khiopsdriver-azure/archive/refs/tags/${{ version }}.tar.gz
    sha256: be782990a521ae0de2fc88f750b6e077db29e5ab91fd0fc8ebb2f65798f3a80a
  - url: https://github.com/KhiopsML/khiopsdriver-shared/archive/101d6f898003cf794cd695f3fa0afc66f8d7afa5.tar.gz
    sha256: cc2bc0c880b17a540488e9c74960f01b2d1b4a848b3a27cff9948f7e8c19e182
    target_directory: shared

build:
  number: 1

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja
  host:
    - spdlog
    - azure-identity-cpp ==1.13.0
    - azure-storage-blobs-cpp ==12.14.0
    - azure-storage-files-shares-cpp ==12.14.0

tests:
  - script:
      - if: unix
        then: test -f $PREFIX/lib/libkhiopsdriver_file_azure${SHLIB_EXT}
        else:
          - if not exist %PREFIX%\Library\bin\libkhiopsdriver_file_azure.dll exit 1

about:
  homepage: https://khiops.org
  license: BSD-3-Clause-Clear
  license_file: LICENSE
  summary: Khiops driver to access files on Azure Cloud Storage
  description: The Azure driver plugin extends Khiops to enable processing of data files located on Azure Cloud Storage

extra:
  recipe-maintainers:
    - tristandeb1
    - sgouache
